const DISCOVERY = "DISCOVERY"
const NEW_PEOPLE = "NEW_PEOPLE"
const RECENTLY_ONLINE = "RECENTLY_ONLINE"
const MATCHING_SEARCH_CRITERIA = "MATCHING_SEARCH_CRITERIA"
const MATCHING_INTERESTS = "MATCHING_INTERESTS"

module.exports = {
    DISCOVERY,
    NEW_PEOPLE,
    RECENTLY_ONLINE,
    MATCHING_SEARCH_CRITERIA,
    MATCHING_INTERESTS
}